# Generated by Django 2.2.5 on 2019-09-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('has_live_subscription', models.BooleanField(default=False)),
                ('has_active_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('uuid', models.CharField(max_length=150)),
                ('plan_code', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscription', to='recurly_acount.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('uuid', models.CharField(max_length=150)),
                ('plan_code', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plan', to='recurly_acount.Subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('uuid', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=100)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurly_acount.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
