# Generated by Django 2.2.5 on 2019-09-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurly_acount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_uploaded',
        ),
    ]
